batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 14
model_path: Trained_Models/03_handwriting_recognition\my_handwriting_small
train_epochs: 1000
train_workers: 20
vocab: AkshwrvfncpqxdiMgmjotulybaez
width: 128
