batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 28
model_path: Trained_Models/03_handwriting_recognition/my_handwriting_med_CER
train_epochs: 1000
train_workers: 20
vocab: vhC31GTrRSUnLo2kxq4BWPQlEwd&,jOHFcsY0tA+Dy7eN$ipgzM)ua6IV5(J-8b9Zmf.
width: 128
